# https://docs.flutter.dev/development/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file
arb-dir: lib/l10n
template-arb-file: app_ar.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
preferred-supported-locales:
- "ar"
- "en"
- "zh"
use-deferred-loading: true
untranslated-messages-file: docs/untranslated.json
